// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbZgnpMJEwgL5k42jyQDb3ek_w6vZ0g4',
    appId: '1:994753416767:web:bbfda0bf4436f2ac85728a',
    messagingSenderId: '994753416767',
    projectId: 'crud-auth-test-e7cf2',
    authDomain: 'crud-auth-test-e7cf2.firebaseapp.com',
    storageBucket: 'crud-auth-test-e7cf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1pf9PIW0uPQdAaaBx3nj_2dx3lQ36To',
    appId: '1:994753416767:android:dee4403bbfe100c785728a',
    messagingSenderId: '994753416767',
    projectId: 'crud-auth-test-e7cf2',
    storageBucket: 'crud-auth-test-e7cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZaVCdBMwuWYwt8wkTCNLhpoKnF0pF5Lo',
    appId: '1:994753416767:ios:c69929abc875ff9285728a',
    messagingSenderId: '994753416767',
    projectId: 'crud-auth-test-e7cf2',
    storageBucket: 'crud-auth-test-e7cf2.appspot.com',
    iosBundleId: 'com.example.crudAuthTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZaVCdBMwuWYwt8wkTCNLhpoKnF0pF5Lo',
    appId: '1:994753416767:ios:c69929abc875ff9285728a',
    messagingSenderId: '994753416767',
    projectId: 'crud-auth-test-e7cf2',
    storageBucket: 'crud-auth-test-e7cf2.appspot.com',
    iosBundleId: 'com.example.crudAuthTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCbZgnpMJEwgL5k42jyQDb3ek_w6vZ0g4',
    appId: '1:994753416767:web:1a05fbe139bea1d785728a',
    messagingSenderId: '994753416767',
    projectId: 'crud-auth-test-e7cf2',
    authDomain: 'crud-auth-test-e7cf2.firebaseapp.com',
    storageBucket: 'crud-auth-test-e7cf2.appspot.com',
  );
}
